# Generated by Django 2.1.3 on 2019-02-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=60)),
                ('lastUpdate', models.DateTimeField()),
                ('numBikes', models.IntegerField()),
                ('numStands', models.IntegerField()),
                ('availableStands', models.IntegerField()),
            ],
        ),
    ]
